### ISSUE TITLE
Crash After Master Password Recovery

### ISSUE THREAD

**Issue by stephen-smith** [jelmerk/maven-settings-decoder#1]
```
Exception in thread "main" org.sonatype.plexus.components.cipher.PlexusCipherException: java.lang.NegativeArraySizeException
        at org.sonatype.plexus.components.cipher.PBECipher.decrypt64(PBECipher.java:193)
        at org.sonatype.plexus.components.cipher.DefaultPlexusCipher.decrypt(DefaultPlexusCipher.java:72)
        at org.sonatype.plexus.components.cipher.DefaultPlexusCipher.decryptDecorated(DefaultPlexusCipher.java:89)
        at org.github.jelmerk.maven.settings.Decorder.decodePassword(Decorder.java:66)
        at org.github.jelmerk.maven.settings.Decorder.printPasswords(Decorder.java:107)
        at org.github.jelmerk.maven.settings.Decorder.main(Decorder.java:61)
Caused by: java.lang.NegativeArraySizeException
        at org.sonatype.plexus.components.cipher.PBECipher.decrypt64(PBECipher.java:179)
        ... 5 more
```

**Comment by stephen-smith** [comment]
```java-version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```

**Comment by stephen-smith** [comment]
Using the compiled distributable on `CYGWIN_NT-6.1-WOW ADMINIB-T02RGPK 2.6.0(0.304/5/3) 2016-08-31 14:27 i686 Cygwin`

**Comment by stephen-smith** [comment]
Caused by having a server that does not have a encrypted password, I think.  I commented out the entries with a plain-text password and it gave me the rest.

**Comment by stephen-smith** [comment]
PR #2 is my proposed fix.

**Comment by lgrill-pentaho** [comment]
Duplicated the behavior that Stephen describes:
Apache Maven 3.3.9
java version 1.8.0_111
Darwin Kernel Version 16.6.0
