### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by david0** [jelmerk/maven-settings-decoder#4]
Sadly does not work for me:
```
./bin/maven-settings-decoder -f ~/.m2/settings.xml -s ~/.m2/settings-security.xml 
Master password is : <my username>
Exception in thread "main" org.sonatype.plexus.components.cipher.PlexusCipherException: java.lang.ArrayIndexOutOfBoundsException
	at org.sonatype.plexus.components.cipher.PBECipher.decrypt64(PBECipher.java:193)
	at org.sonatype.plexus.components.cipher.DefaultPlexusCipher.decrypt(DefaultPlexusCipher.java:72)
	at org.sonatype.plexus.components.cipher.DefaultPlexusCipher.decryptDecorated(DefaultPlexusCipher.java:89)
	at org.github.jelmerk.maven.settings.Decorder.decodePassword(Decorder.java:67)
	at org.github.jelmerk.maven.settings.Decorder.printPasswords(Decorder.java:109)
	at org.github.jelmerk.maven.settings.Decorder.main(Decorder.java:62)
Caused by: java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at org.sonatype.plexus.components.cipher.PBECipher.decrypt64(PBECipher.java:175)
	... 5 more
```

**Comment by jglick** [comment]
Worked for me for many passwords, then crashed on one with

```
Exception in thread "main" org.sonatype.plexus.components.cipher.PlexusCipherException: java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 8 out of bounds for byte[6]
	at org.sonatype.plexus.components.cipher.PBECipher.decrypt64(PBECipher.java:193)
	at org.sonatype.plexus.components.cipher.DefaultPlexusCipher.decrypt(DefaultPlexusCipher.java:72)
	at org.sonatype.plexus.components.cipher.DefaultPlexusCipher.decryptDecorated(DefaultPlexusCipher.java:89)
	at org.github.jelmerk.maven.settings.Decorder.decodePassword(Decorder.java:67)
	at org.github.jelmerk.maven.settings.Decorder.printPasswords(Decorder.java:109)
	at org.github.jelmerk.maven.settings.Decorder.main(Decorder.java:62)
Caused by: java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 8 out of bounds for byte[6]
	at java.base/java.lang.System.arraycopy(Native Method)
	at org.sonatype.plexus.components.cipher.PBECipher.decrypt64(PBECipher.java:175)
	... 5 more
```

**Comment by jelmerk** [comment]
If you have something i can reproduce this with i can take a look 

Though i guess given the nature of the files that may be tricky...

**Comment by jglick** [comment]
I think it is just #2 actually.

**Comment by david0** [comment]
Just stumbled again over that. Unfortunatley its not easy to help you reproducing that, since I don't know how this password was created. Its not a plaintext password. https://github.com/ci-and-cd/maven-settings-decoder works for me btw.
